runtime: python27
api_version: 1
threadsafe: yes


handlers:
- url: /static
  script: static
- url: .*  # This regex directs all routes to final.app
  script: mobileWeb.app


#libraries:
#- name: jinja2
#  version: latest
